Owlot/refactor with lib common
Arrow-air/svc-assets pull request #19
Opened 2023-06-21 16:40 UTC by owlot

2023-06-21 20:00 UTC, ServiceDog requested changes
Looks great! Just one failing test

2023-06-26 19:00 UTC, owlot commented
> Looks great! Just one failing test

fixed!

2023-06-26 23:53 UTC, ServiceDog requested changes

2023-06-26 23:53 UTC, ServiceDog commented on client-rest/Cargo.toml
>  description = "Arrow Storage service REST client"
assets service

2023-06-27 14:48 UTC, owlot commented on client-rest/Cargo.toml
>  description = "Arrow Storage service REST client"
fixed!

2023-06-27 18:54 UTC, ServiceDog approved these changes

2023-06-27 18:54 UTC, merged